### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Tyrn** [emacsorphanage/key-chord#5]
Hi,

Is there a way to make the timeout a bit longer? On my keyboard I can tap a key twice fast enough, but I can't move my index finger from `j` to `h` in time.

**Comment by Tyrn** [comment]
The solution:
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(key-chord-two-keys-delay 0.2)
 '(key-chord-one-key-delay 0.3)
 ...
 )
```

**Comment by tarsius** [comment]
I think https://github.com/emacsorphanage/key-chord/pull/2 might take care of this.

**Comment by BlueDrink9** [comment]
my reading is that Tyrn found the solution in their previous comment. two-keys-delay is sufficient to increase the timeout between j and h, #2 is unneeded
