### ISSUE TITLE
Increased failure rate since last update

### ISSUE THREAD

**Issue by reedrolemodel** [emacsorphanage/key-chord#6]
The commit https://github.com/emacsorphanage/key-chord/commit/e724def60fdf6473858f2962ae276cf4413473eb seems to have affected the way key-chords are detected in such a way that I frequently encounter failure to activate key-chords now. Instead of running the key-chord defined command, I get two characters inserted. I'm not sure how `key-chord-safety-interval-backward` and `key-chord-safety-interval-forward` affect the previous behavior. Previously it seems there was no regard to whether other keys were pressed before or after key-chords. So if I wanted to restore that would I set both safety-intervals to zero?

**Comment by NicholasBHubbard** [comment]
This commit caused me confusion. To fix the problem I set `key-chord-safety-interval-backward` and `key-chord-safety-interval-forward` to 0.

I think that the default values for these need to be changed and documented in the README.

**Comment by kwrooijen** [comment]
I'm having the same issue. I have `xs` mapped to save buffer, but now when I type something and quickly press `xs` it doesn't work anymore. Instead it just inserts "xs" into the buffer.

 I set both `key-chord-safety-interval-backward` and `key-chord-safety-interval-forward` to 0, but it doesn't resolve it for me.

**Comment by boechat107** [comment]
> This commit caused me confusion. To fix the problem I set `key-chord-safety-interval-backward` and `key-chord-safety-interval-forward` to 0.

This also didn't work for me.

I was able to pin `key-chord`'s version using [`quelpa`](https://github.com/quelpa/quelpa):

```emacs
;; Uninstall "key-chord" using "package-delete" first.
(quelpa
  '(key-chord
   :fetcher github
   :repo "emacsorphanage/key-chord"
   :commit "68264d09593e69c1d4773859ac570bd9feb008d9"))
```

**Comment by rmolinari** [comment]
I found success using these settings along with the changes suggested by @rthewitt in #7.
```elisp
(use-package key-chord
  :custom
  (key-chord-one-key-delay 0.05)
  (key-chord-two-keys-delay 0.10)
  ;;; A 2023 release caused problems and delays. See
  ;;; - https://github.com/emacsorphanage/key-chord/issues/6
  ;;; - https://github.com/emacsorphanage/key-chord/issues/7
  (key-chord-safety-interval-forward 0.1)
  (key-chord-safety-interval-backward 0)
  (key-chord-safety-interval-forward 0)

  :init
  (use-package use-package-chords)

  (key-chord-mode 1)
  ;;; etc
)
```

**Comment by tarsius** [comment]
I've reverted the commit that caused this.
