### ISSUE TITLE
reponse slow on emacs 29

### ISSUE THREAD

**Issue by sawyerzheng** [emacsorphanage/key-chord#7]
on emacs 29,  key-chord calls comand will delay about one second, however normal key bindings like define-key has no delay.

**Comment by Flinner** [comment]
happens to me too :(

**Comment by choltz** [comment]
Same on Emacs 28.2

**Comment by rmolinari** [comment]
I also see this on 29.1, ~~but it was fine for me on 28.2.~~

Actually, I also see the slowness when I go back to 28.2. My guess is that an update to some other package is causing this. I will see if I can find out more.

I'm on a Mac using the railwaycat port of Emacs

**Comment by rthewitt** [comment]
The slowdown occurred for me _without_ updating Emacs or the package itself.  I deleted (and backed up) my .emacs.d directory when updating other packages.  Afterward I found my key-chords very slow even though a diff showed that the package contents had not changed at all.  Same version, same files.

I'm on Emacs 29.0.60

For me the solution was to customize the variables

`key-chord-two-keys-delay` and `key-chord-safety-interval-forward`.  It was the latter that was causing the delay.

I use key-chord to remap `ESC` in Evil mode.  Here is my use-package config as an example.  Hopefully it helps someone.

```
(use-package key-chord
  :after evil
  :custom
  (key-chord-two-keys-delay 0.05)
  (key-chord-safety-interval-forward 0.1)
  :config
  (key-chord-mode 1)
  (key-chord-define evil-insert-state-map  "jk" 'evil-normal-state)
  (key-chord-define evil-replace-state-map  "jk" 'evil-normal-state))
```

**Comment by Flinner** [comment]
Thanks @rthewitt , I can confirm it solves my issue. Was an annoying two weeks without key-chord

**Comment by sawyerzheng** [comment]
It's also works for me on emacs 29.1.50. Thank you @rthewitt .

**Comment by tarsius** [comment]
I've reverted the commit that caused this.

**Comment by AnabasisXu** [comment]
Somehow I felt the text input is still slower under key-chord mode in Emacs 31. Switch on and off key-chord makes a big difference even though profiler says it only takes 4%:

```elisp
         121  62% - redisplay_internal (C function)
           1   0%  - eval
           1   0%     format
           1   0%  - jit-lock-function
           1   0%   - jit-lock-fontify-now
           1   0%      #<byte-code-function 840>
          26  13% - command-execute
          26  13%  - byte-code
          26  13%   + read-extended-command
          23  11% - ...
          23  11%  + completion--nth-completion
          16   8%   Automatic GC
           8   4% - key-chord-input-method
           8   4%  - sit-for
           6   3%     redisplay_internal (C function)
```
