### ISSUE TITLE
if: Wrong number of arguments: sit-for, 3 in Emacs 30.0 after 2023-10-10

### ISSUE THREAD

**Issue by GregorZattler** [emacsorphanage/key-chord#9]
The last Emacs build which worked for me was from ce3ed6e019cdb5f8fd831e35c04832aaa2c768b6 while b36e2b1772680b8fce067c6ea2cdf582af982aaa did not work, the error message is: "if: Wrong number of arguments: sit-for, 3" or "key-chord-input-method: Wrong number of arguments: #<subr sit-for" if byte-and-native compiled.

Changing the line

(sit-for delay 0  'no-redisplay))

to 

(sit-for delay  'no-redisplay))

in 

key-chord-input-method 

somehow seems have to fixed the issue (for now and me at least).

It would be nice if someone with knowledge could really fix this.

P.S.:

I also did a git bisect of the last Emacs commits, but I have no idea why a change in an erc file should affect key-chord:

     5e2be1e0ba64f030b8493d3e7b93b69caba3a254 is the first bad commit
     commit 5e2be1e0ba64f030b8493d3e7b93b69caba3a254 
     Author: F. Jason Park <jp@neverwas.me>
     Date:   Tue Oct 10 00:32:21 2023 -0700

        Swap hook positions of erc-fill and erc-match-message

        * etc/ERC-NEWS: Fix new order of reserved modify-hook members.
        * lisp/erc/erc-fill.el: Increase depth of `erc-fill' in both modify
        hooks from 40 to 60.
        * lisp/erc/erc-match.el (erc-match-mode, erc-match-enable,
        erc-match-disable): Use general module setup function
        `erc-match--setup' for buffer-local modifications instead of calling
        `erc-match--modify-invisibility-spec' directly.  Add and remove new
        post-modify hook `erc-match--on-insert-post'.
        (erc-hide-fools): Use `erc--msg-props' for communicating to
        post-processing step for applying invisible props instead of doing so
        immediately.
        (erc-match--on-insert-post): New function to apply module-specific
        `invisible' props.  Will likely be replaced by a general service to do
        the same, perhaps provided by a future "erc-ignore"-like module.
        (erc-match--modify-invisibility-spec, erc-match--setup): Rename former
        to latter and only operate on current buffer.
        * test/lisp/erc/erc-scenarios-match.el
        (erc-scenarios-match--stamp-left-fools-invisible,
        erc-scenarios-match--stamp-right-fools-invisible,
        erc-scenarios-match--stamp-right-invisible-fill-wrap,
        erc-scenarios-match--stamp-both-invisible-fill-static): Update
        expected order of ERC-owned `invisible' prop members `match-fools' and
       `timestamp'.
       * test/lisp/erc/erc-tests.el (erc--essential-hook-ordering): Swap
        expected order of `erc-fill' and `erc-add-timestamp' in both hooks.
        (Bug#64301)

**Comment by oscarfv** [comment]
Are you using a recent version of `key-chord`? This problem was fixed years ago:

https://github.com/emacsorphanage/key-chord/commit/68523a3b480300a670ecb9df52e56fec1b60cd03

**Comment by GregorZattler** [comment]
* oscarfv ***@***.***> [2023-11-19; 06:29 -08]:
> Are you using a recent version of `key-chord`? This problem was fixed years ago:
>
> https://github.com/emacsorphanage/key-chord/commit/68523a3b480300a670ecb9df52e56fec1b60cd03

thanks.  You made me realize that using melpa-stable
does not necessarily mean that you are on the stable
side then...

Is there a way to inform somebody, that the
melpa-stable version is not helpful here?

Ciao; Gregor

**Comment by tarsius** [comment]
I've just created a release.
